# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f3bef053b51daecb876a53b5d279e9dc4ac6f8cb84e4df40b3b0e3972fb9d4e8cd05ea89d497e43998a0951481c092c0ee6fe91f2372d9524d77ea7ccdf1f63

test:
  secret_key_base: 83a26731d275a6ad222469f7e1b9e04392bd0f8b481188a8ec78690e434ee6f7703e61b820ade6d4ac717b1df33a222950d6837f145837b0ed2d157d87741ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
